[project]
name = "spotify-textualize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "spotipy>=2.24.0",
    "textual>=0.83.0",
]
